/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos;

import java.text.SimpleDateFormat;
import java.util.TimerTask;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author jamer
 */
public class JGui extends javax.swing.JFrame {
    java.util.Timer timer1 = new java.util.Timer();
    public int tempoMinutos = 0;
    public int tempoSegundos = 0;
    public int delay = 1000;   // funcao Timer
    public int interval = 1000;  // funcao Timer
    public boolean timerAtivado = false;
    public boolean painelOp;
    /**
     * Creates new form JGui
     */
    public JGui() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCores = new javax.swing.ButtonGroup();
        painelOpcoes = new javax.swing.JPanel();
        lblEstiloLivre = new javax.swing.JLabel();
        lblInciar = new javax.swing.JLabel();
        lblReiniciar = new javax.swing.JLabel();
        lblOpcoes = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        pnlOpcoes = new javax.swing.JPanel();
        lblRoxo = new javax.swing.JLabel();
        lblAmarelo = new javax.swing.JLabel();
        lblAzulClaro = new javax.swing.JLabel();
        lblCinza = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCronometro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPomodoro");
        setBackground(new java.awt.Color(255, 204, 153));

        painelOpcoes.setBackground(new java.awt.Color(204, 204, 255));

        lblEstiloLivre.setFont(new java.awt.Font("Rachana", 0, 14)); // NOI18N
        lblEstiloLivre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblInciar.setBackground(new java.awt.Color(204, 204, 255));
        lblInciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInciar.setText("Pomodoro");
        lblInciar.setOpaque(true);
        lblInciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInciarMouseClicked(evt);
            }
        });

        lblReiniciar.setBackground(new java.awt.Color(204, 204, 255));
        lblReiniciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblReiniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReiniciar.setText("Descanço");
        lblReiniciar.setOpaque(true);
        lblReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReiniciarMouseClicked(evt);
            }
        });

        lblOpcoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOpcoes.setText(" ...");
        lblOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpcoesMouseClicked(evt);
            }
        });

        lblFechar.setBackground(new java.awt.Color(255, 0, 0));
        lblFechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechar.setText("X");
        lblFechar.setOpaque(true);
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        pnlOpcoes.setBackground(new java.awt.Color(204, 204, 255));

        lblRoxo.setBackground(new java.awt.Color(153, 102, 255));
        lblRoxo.setOpaque(true);

        lblAmarelo.setBackground(new java.awt.Color(255, 255, 153));
        lblAmarelo.setOpaque(true);
        lblAmarelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAmareloMouseClicked(evt);
            }
        });

        lblAzulClaro.setBackground(new java.awt.Color(204, 255, 204));
        lblAzulClaro.setOpaque(true);

        lblCinza.setBackground(new java.awt.Color(204, 204, 204));
        lblCinza.setOpaque(true);

        jLabel2.setText("Atividades em execução:");

        jLabel3.setText("0");

        jLabel4.setText("Concluidas: ");

        jLabel5.setText("0");

        javax.swing.GroupLayout pnlOpcoesLayout = new javax.swing.GroupLayout(pnlOpcoes);
        pnlOpcoes.setLayout(pnlOpcoesLayout);
        pnlOpcoesLayout.setHorizontalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(lblRoxo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAzulClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOpcoesLayout.setVerticalGroup(
            pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAzulClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoxo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout painelOpcoesLayout = new javax.swing.GroupLayout(painelOpcoes);
        painelOpcoes.setLayout(painelOpcoesLayout);
        painelOpcoesLayout.setHorizontalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInciar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstiloLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelOpcoesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelOpcoesLayout.setVerticalGroup(
            painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelOpcoesLayout.createSequentialGroup()
                .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelOpcoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInciar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(lblReiniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEstiloLivre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        pnlOpcoes.setVisible(false);

        lblCronometro.setBackground(new java.awt.Color(204, 204, 255));
        lblCronometro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCronometro.setForeground(new java.awt.Color(0, 0, 0));
        lblCronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronometro.setText("00:00:00");
        lblCronometro.setOpaque(true);

        campoTexto.setColumns(20);
        campoTexto.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        campoTexto.setRows(5);
        campoTexto.setLineWrap(true);
        jScrollPane1.setViewportView(campoTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(painelOpcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
            .addComponent(lblCronometro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCronometro, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpcoesMouseClicked

        if (painelOp) {
            System.out.println("bug1");
            pnlOpcoes.setVisible(false);
            
        } else {
            System.out.println("bug2");
            pnlOpcoes.setVisible(true);
            
        }
        /*if (painelOp == false) {
            pnlOpcoes.setVisible(true);
        }
        if (painelOp == true) {
            pnlOpcoes.setVisible(false);
        }
        */
        
    }//GEN-LAST:event_lblOpcoesMouseClicked

    private void lblAmareloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmareloMouseClicked
        campoTexto.setBackground(new java.awt.Color(255, 255, 204));

    }//GEN-LAST:event_lblAmareloMouseClicked

    private void lblInciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInciarMouseClicked
        timerAtivado = true; // programa em funcionamento
        
        timer1.scheduleAtFixedRate(new TimerTask() {
                public void run() {
                    /* System.out.println("Debugg btnIniciar"); */
                    /* Converte o valor inteiro em String para exibir no label */
                    String tempoConvSegundos = String.valueOf(tempoSegundos);
                    String tempoConvMinutos = String.valueOf(tempoMinutos);
                    tempoSegundos++;
                    lblCronometro.setText("00:"+tempoConvMinutos+":"+tempoConvSegundos);
                    if (tempoSegundos == 60) {
                        tempoMinutos++;
                        tempoSegundos = 0;
                    
                    }
                    if (tempoMinutos == 25) {
                        JOptionPane.showMessageDialog(null, "Ciclo esgotado\n! Descanse durante 5 minutos e volte as atividades.", "Você precisa fazer uma pausa", JOptionPane.ERROR_MESSAGE, null);
                        timer1.cancel();
                        timer1.purge();
                    }
                    
                }
            
        }, delay, interval);          
        
        
    }//GEN-LAST:event_lblInciarMouseClicked

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReiniciarMouseClicked
        timerAtivado = false; // desligado
        timer1.cancel();
        tempoSegundos = 0;
        tempoMinutos = 0;
        lblCronometro.setText("00:00:00");
    }//GEN-LAST:event_lblReiniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoTexto;
    private javax.swing.ButtonGroup grupoCores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmarelo;
    private javax.swing.JLabel lblAzulClaro;
    private javax.swing.JLabel lblCinza;
    private javax.swing.JLabel lblCronometro;
    private javax.swing.JLabel lblEstiloLivre;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblInciar;
    private javax.swing.JLabel lblOpcoes;
    private javax.swing.JLabel lblReiniciar;
    private javax.swing.JLabel lblRoxo;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel pnlOpcoes;
    // End of variables declaration//GEN-END:variables
}
